name: 'tickup-se/notify_opsgenie'
description: 'Send an incident to OpsGenie'
author: 'TickUp'

branding:
  icon: 'activity'
  color: 'orange'

inputs:
  message:
    description: 'Alert message'
    required: false
    default: ""
  description:
    description: 'Alert description'
    required: false
    default: ""
  priority:
    description: 'Priority level'
    required: true
  api_key:
    description: 'OpsGenie API Key'
    required: true
  team:
    description: 'Team'
    required: true
  tag:
    description: 'Optional tag'
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "/app/action"
    - ${{ inputs.message }}
    - ${{ inputs.description }}
    - ${{ inputs.priority }}
    - ${{ inputs.api_key }}
    - ${{ inputs.team }}
    - ${{ inputs.tag }}