name: 'tickup-se/notify_opsgenie'
description: 'Send an incident to OpsGenie'
author: 'TickUp'

branding:
  icon: 'x'
  color: 'red'

inputs:
  priority:
    description: 'Priority level'
    required: true
  message:
    description: 'Alert message'
    required: true
  api_key:
    description: 'OpsGenie API Key'
    required: true
  team:
    description: 'Team tag'
    required: true
  tags:
    description: 'Optional tags'
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "/app/action"
    - ${{ inputs.message }}
    - ${{ inputs.priority }}
    - ${{ inputs.api_key }}
    - ${{ inputs.team }}
    - ${{ inputs.tags }}